name: Publish to WinGet

on:
  workflow_run:
    workflows: ["Build FreeShow Madely - Windows"]
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: WinGet Releaser
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: ChurchApps.FreeShow
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: vassbo
